[connections.snowflake]
account = "BCKHPWS-BIB87396"
user = "TURTLE"
password = "eyJraWQiOiI2Nzg4ODA5OTkyMDgxNDE0IiwiYWxnIjoiRVMyNTYifQ.eyJwIjoiNDA0NjQ0NjEyOjQwNDY0NDYxMiIsImlzcyI6IlNGOjEwNDkiLCJleHAiOjE3NzE0NDAxNzZ9.-UVBmGwEZuJ6oVf9h1G2Ea389Z5JvhBEuPkSjDOuHwod3IibvpyV-UpwTGI4mQQRn5kvXkCavVf_wIvLAu_qXA"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
